language: node_js

node_js:  
  - "stable"

services:
  - mongodb
  - postgresql

addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server

before_script:
  - psql -c 'create database jsreport;' -U postgres
